version: '2'

networks:
  Mynet2:
services:
  sqlserver:
    image: imdbserver:latest
    networks:
    - Mynet2
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password@123"
    ports:
    - '1433:1433'
  webserver:
    depends_on:
    - sqlserver
    tty: true
    image: imwebapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    networks:
    - Mynet2
    environment:
      COMPOSE_HTTP_TIMEOUT: "1000"
